youtube: https://www.youtube.com/channel/UCSLuDXxxql4EVK_Ktd6PNbw # Main channel: https://www.youtube.com/channel/UCWVDjAcecHHa8UrEWMRGI8w
twitter: https://twitter.com/McHorsy
github: https://github.com/mchorse
reddit: https://www.reddit.com/r/mcpub/
discord: https://discord.gg/qfxrqUF
minema: https://github.com/daipenger/minema/releases
blockbench: https://blockbench.net/
geckolib: 
    title: GeckoLib    
    curse: https://curseforge.com/minecraft/mc-mods/geckolib

# MachinimaHub
hub: 
    banner: https://i.imgur.com/jrK0WA2.png
    invite: https://discord.gg/4YFUmJp

# Human readable titles
titles:
    pmc: Planet Minecraft page
    curse: CurseForge page
    github: GitHub

aperture:
    title: Aperture
    
    banner: https://i.imgur.com/Wras78u.png
    cover: https://i.imgur.com/rckGnn4.png
    
    pmc: https://www.planetminecraft.com/mod/aperture-3978432/
    curse: https://www.curseforge.com/minecraft/mc-mods/aperture
    github: https://github.com/mchorse/aperture
    wiki: https://github.com/mchorse/aperture/wiki

blockbuster:
    title: Blockbuster
    
    # Brand images
    banner: https://i.imgur.com/fkRVMIw.png
    cover: http://i.imgur.com/XgU8Tvx.png
    
    # Mod pages
    pmc: http://www.planetminecraft.com/mod/blockbuster-machinima-mod/
    curse: https://www.curseforge.com/minecraft/mc-mods/blockbuster
    github: https://github.com/mchorse/blockbuster
    wiki: https://github.com/mchorse/blockbuster/wiki

chameleon:
    title: Chameleon

    banner: https://i.imgur.com/Iobi4O0.png
    cover: https://i.imgur.com/BqozBzt.png

    curse: https://curseforge.com/minecraft/mc-mods/chameleon-morph
    github: https://github.com/mchorse/chameleon
    wiki: https://github.com/mchorse/chameleon/wiki

commander:
    title: Commander

    # Brand images
    banner: https://i.imgur.com/IFxwMOd.png
    cover: https://i.imgur.com/rzHbVzC.png

    # Mod pages
    pmc: http://www.planetminecraft.com/mod/blockbuster-machinima-mod/
    curse: https://www.curseforge.com/minecraft/mc-mods/commander
    github: https://github.com/mchorse/commander

emoticons: 
    title: Emoticons
    
    # Brand images
    banner: https://i.imgur.com/do30WtA.png
    cover: https://i.imgur.com/vih4m0S.png
    
    # PMC
    pmc: https://www.planetminecraft.com/mod/emoticons-4212245/
    curse: https://www.curseforge.com/minecraft/mc-mods/emoticons

mappet:
    title: Mappet

    banner: https://i.imgur.com/1pvpWDH.png

    curse: https://www.curseforge.com/minecraft/mc-mods/mappet
    github: https://github.com/mchorse/mappet
    wiki: https://github.com/mchorse/mappet/wiki
    discord: https://discord.gg/QhvbgSWpYn

mclib:
    title: McLib

    curse: https://www.curseforge.com/minecraft/mc-mods/mchorses-mclib
    github: https://github.com/mchorse/mclib

metamorph:
    title: Metamorph
    
    # Brand images
    banner: http://i.imgur.com/gbHB5iQ.png
    cover: http://i.imgur.com/E7fdU9m.png
    
    # Mod pages
    pmc: http://www.planetminecraft.com/mod/metamorph/
    curse: https://www.curseforge.com/minecraft/mc-mods/metamorph
    github: https://github.com/mchorse/metamorph
    wiki: https://github.com/mchorse/metamorph/wiki