youtube: https://www.youtube.com/channel/UCSLuDXxxql4EVK_Ktd6PNbw # Main channel: https://www.youtube.com/channel/UCWVDjAcecHHa8UrEWMRGI8w
twitter: https://twitter.com/McHorsy
github: https://github.com/mchorse
reddit: https://www.reddit.com/r/mcpub/
discord: https://discord.gg/qfxrqUF
minema: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2790594-minema-unofficial-the-smooth-movie-recorder

# Human readable titles
titles:
    pmc: Planet Minecraft page
    mcforum: Minecraft Forum thread
    curse: CurseForge page
    github: Source code
    adfly: AdFly support link

aperture:
    title: Aperture
    
    banner: https://i.imgur.com/Wras78u.png
    cover: https://i.imgur.com/rckGnn4.png
    
    pmc: https://www.planetminecraft.com/mod/aperture-3978432/
    mcforum: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2837982-aperture-an-advanced-camera-mod
    curse: https://minecraft.curseforge.com/projects/aperture
    github: https://github.com/mchorse/aperture
    wiki: https://github.com/mchorse/aperture/wiki

blockbuster:
    title: Blockbuster
    
    # Brand images
    banner: http://i.imgur.com/nqDKg1R.png
    cover: http://i.imgur.com/XgU8Tvx.png
    
    # Mod pages
    pmc: http://www.planetminecraft.com/mod/blockbuster-machinima-mod/
    mcforum: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2700216-blockbuster-machinima-studio-mod
    curse: https://minecraft.curseforge.com/projects/blockbuster
    github: https://github.com/mchorse/blockbuster
    adfly: http://adf.ly/15268913/blockbuster-curseforge
    wiki: https://github.com/mchorse/blockbuster/wiki

commander:
    title: Commander

    # Brand images
    banner: https://i.imgur.com/IFxwMOd.png
    cover: https://i.imgur.com/rzHbVzC.png

    # Mod pages
    pmc: http://www.planetminecraft.com/mod/blockbuster-machinima-mod/
    mcforum: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2700216-blockbuster-machinima-studio-mod
    curse: https://minecraft.curseforge.com/projects/commander
    github: https://github.com/mchorse/commander

emoticons: 
    title: Emoticons
    
    # Brand images
    banner: https://i.imgur.com/do30WtA.png
    cover: https://i.imgur.com/vih4m0S.png
    
    # PMC
    pmc: https://www.planetminecraft.com/mod/emoticons-4212245/
    curse: https://minecraft.curseforge.com/projects/emoticons

mclib:
    title: McLib

    curse: https://minecraft.curseforge.com/projects/mchorses-mclib
    github: https://github.com/mchorse/mclib

metamorph:
    title: Metamorph
    
    # Brand images
    banner: http://i.imgur.com/gbHB5iQ.png
    cover: http://i.imgur.com/E7fdU9m.png
    
    # Mod pages
    pmc: http://www.planetminecraft.com/mod/metamorph/
    mcforum: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2753214-metamorph-morph-into-vanilla-mobs
    curse: https://minecraft.curseforge.com/projects/metamorph
    github: https://github.com/mchorse/blockbuster
    adfly: http://adf.ly/15268913/metamorph-curseforge
    wiki: https://github.com/mchorse/metamorph/wiki